// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409140306_order_check")]
    partial class order_check
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CH_User_Role", "[Role] IN ('Admin','User')");
                        });
                });

            modelBuilder.Entity("Data.Models.Main.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Data.Models.Main.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EducationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PassportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EducationId")
                        .IsUnique();

                    b.HasIndex("Inn")
                        .IsUnique();

                    b.HasIndex("PassportId")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Employees", t =>
                        {
                            t.HasCheckConstraint("CH_Employee_BirthDate", "[BirthDate] <= GETDATE()");

                            t.HasCheckConstraint("CH_Employee_Gender", "[Gender] IN ('Male','Female')");

                            t.HasCheckConstraint("CH_Employee_Inn", "LEN([Inn]) IN (12, 14)");

                            t.HasCheckConstraint("CH_Employee_PhoneNumber", "LEN([PhoneNumber]) BETWEEN 10 AND 16");
                        });
                });

            modelBuilder.Entity("Data.Models.Main.EmployeeEducation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GraduationYear")
                        .HasColumnType("int");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeEducations", t =>
                        {
                            t.HasCheckConstraint("CH_EmployeeEducation_Qualification", "[Qualification] IN ('Secondary','SecondarySpecial','Bachelor','Master','Specialist','PhD')");

                            t.HasCheckConstraint("CH_EmployeeEducation_Specialization", "[Specialization] IN ('SoftwareEngineering','InformationSystems','AppliedInformatics','CyberSecurity','Economics','Accounting','Finance','Management','HumanResources','Marketing','Law','PublicAdministration','Logistics','CivilEngineering','ElectricalEngineering')");
                        });
                });

            modelBuilder.Entity("Data.Models.Main.EmployeePassport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("GivenBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.ToTable("EmployeePassports");
                });

            modelBuilder.Entity("Data.Models.Main.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FireReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HireDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HirePositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("HireDepartmentId");

                    b.HasIndex("HirePositionId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CH_Order_Date", "CAST([Date] AS DATE) >= CAST(GETDATE() AS DATE)");

                            t.HasCheckConstraint("CH_Order_Date_StartDate", "[Date] <= [StartDate]");

                            t.HasCheckConstraint("CH_Order_StartDate_EndDate", "[EndDate] >= [StartDate]");

                            t.HasCheckConstraint("CH_Order_Type", "[Type] IN ('Hire','Fire','StudyLeave','Vacation','BusinessTrip')");
                        });
                });

            modelBuilder.Entity("Data.Models.Main.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Data.Models.Main.Employee", b =>
                {
                    b.HasOne("Data.Models.Main.EmployeeEducation", "Education")
                        .WithOne("Employee")
                        .HasForeignKey("Data.Models.Main.Employee", "EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Main.EmployeePassport", "Passport")
                        .WithOne("Employee")
                        .HasForeignKey("Data.Models.Main.Employee", "PassportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Education");

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("Data.Models.Main.Order", b =>
                {
                    b.HasOne("Data.Models.Main.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Main.Department", "HireDepartment")
                        .WithMany("Orders")
                        .HasForeignKey("HireDepartmentId");

                    b.HasOne("Data.Models.Main.Position", "HirePosition")
                        .WithMany("Orders")
                        .HasForeignKey("HirePositionId");

                    b.Navigation("Employee");

                    b.Navigation("HireDepartment");

                    b.Navigation("HirePosition");
                });

            modelBuilder.Entity("Data.Models.Main.Department", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Data.Models.Main.Employee", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Data.Models.Main.EmployeeEducation", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Models.Main.EmployeePassport", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Models.Main.Position", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
