// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401154415_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CH_User_Role", "[Role] IN ('Admin','User')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ec860f5-bfd3-46d6-9168-2ef53050f121"),
                            Login = "admin",
                            Password = "$2a$11$OswhLeNo0PGwGSGnI0RwTONRZtZUfgw656L0CbJtjY0/L00pvpyea",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Data.Models.Main.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Data.Models.Main.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Inn")
                        .IsUnique();

                    b.HasIndex("Passport")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Employees", t =>
                        {
                            t.HasCheckConstraint("CH_Employee_BirthDate", "[BirthDate] <= GETDATE()");

                            t.HasCheckConstraint("CH_Employee_Inn", "LEN([Inn]) IN (12, 14)");

                            t.HasCheckConstraint("CH_Employee_Passport", "LEN([Passport]) = 11 AND [Passport] LIKE '[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9]'");

                            t.HasCheckConstraint("CH_Employee_PhoneNumber", "LEN([PhoneNumber]) BETWEEN 10 AND 14");
                        });
                });

            modelBuilder.Entity("Data.Models.Main.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FireReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HireDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HirePositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("HireDepartmentId");

                    b.HasIndex("HirePositionId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CH_Order_Date", "[Date] >= GETDATE()");

                            t.HasCheckConstraint("CH_Order_Date_StartDate", "[Date] <= [StartDate]");

                            t.HasCheckConstraint("CH_Order_StartDate_EndDate", "[StartDate] <= [EndDate]");

                            t.HasCheckConstraint("CH_Order_Type", "[Type] IN ('Hire','Fire','StudyLeave','Vacation','BusinessTrip')");
                        });
                });

            modelBuilder.Entity("Data.Models.Main.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Data.Models.Main.Order", b =>
                {
                    b.HasOne("Data.Models.Main.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Main.Department", "HireDepartment")
                        .WithMany("Orders")
                        .HasForeignKey("HireDepartmentId");

                    b.HasOne("Data.Models.Main.Position", "HirePosition")
                        .WithMany("Orders")
                        .HasForeignKey("HirePositionId");

                    b.Navigation("Employee");

                    b.Navigation("HireDepartment");

                    b.Navigation("HirePosition");
                });

            modelBuilder.Entity("Data.Models.Main.Department", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Data.Models.Main.Employee", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Data.Models.Main.Position", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
